### ISSUE TITLE
Problem: Error during rasterization in version 1.4

### ISSUE THREAD

**Issue by emma-burrows** [bzixilu/dotplugin#23]
After I let the plugin update to 1.4, it is loading a blank preview with the caption "Problem: Error during rasterization". I originally noticed this in IntelliJ 2021.2.3 on MacOS Mojave, and the problem persists in the latest version (2021.2.4). I tested it with different versions of the plugin: 

- 1.2 is fine
- 1.3 shows a blank preview and says "No preview is available - Reason: Error during rasterization" at the top of the window
- 1.4 shows a blank preview and shows a copy and a download? icon with the message ""Problem: Error during rasterization" at the bottom of the window.

Graphviz was originally installed via `brew` which lists its version as `graphviz: stable 2.47.2` and `dot` as available on the command line is `dot - graphviz version 2.47.2 (20210527.0053)`

**Comment by bzixilu** [comment]
@emma-burrows Could you please check that the new version (1.4.1) of the plugin solves this problem in your environment?

**Comment by emma-burrows** [comment]
Spam filter ate the ping but I'd noticed the new version and just came here to say the problem was indeed fixed in 1.4.1! Thanks for such a speedy solution - hopefully you'll find out what was wrong with the more recent version of the `graphviz` library...

**Comment by bzixilu** [comment]
@emma-burrows Thank you for confirming!

**Comment by lzhAndroid** [comment]
mac M1 use 1.4.1 always occurs this problem

**Comment by lzhAndroid** [comment]
dot - graphviz version 2.50.0，plugin version:1.4.1,mac M1 pro,this probelm are not fixed

**Comment by bzixilu** [comment]
@lzhAndroid could you please check whether the problem exists in 1.2v in your environment?

**Comment by lzhAndroid** [comment]
> @lzhAndroid could you please check whether the problem exists in 1.2v in your environment?

install 1.2,show no preview is available.

**Comment by lzhAndroid** [comment]
If I install android studio with intel chip ,it work fine.but install apple chip,it show Error during rasterization

**Comment by bzixilu** [comment]
@IzhAndroid thank you for the details, I'll try to check that's wrong, but it could take some time since I have no required hardware unfortunately

**Comment by lzhAndroid** [comment]
> @IzhAndroid thank you for the details, I'll try to check that's wrong, but it could take some time since I have no required hardware unfortunately

if has new version,i can help you to test it

**Comment by lzhAndroid** [comment]
I see j2v8 is only has x86_64 version.<root url="jar://$PROJECT_DIR$/lib/j2v8_macosx_x86_64-4.6.0.jar!/" />

**Comment by bpedman** [comment]
Had this issue on an M1 mac as well. As @lzhAndroid said, j2v8 is not available on m1 and [probably won't be](https://github.com/eclipsesource/J2V8/issues/556#issuecomment-896128464). There is supposed to be a fallback to either graalvm js or nashorn, however, it seems that jetbrains plugins don't have access to any ScriptEngines through the ScriptEngineManager, instead you have to use `IdeScriptEngineManager`, but that would require extending the graphviz-java library to implement your own `GraphvizEngine`. 

Luckily graphviz-java also searches your PATH for `dot` on the command line to do the rendering, so we just need to install graphviz and then make sure its on the path. To do that, I did:

```
brew install graphviz
# Assumes homebrew prefix is /opt/homebrew
sudo launchctl config user path /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbi
```
Reboot, then re-open intellij and it should work.
